### PR TITLE
Fix variable duration in setTimeOut action

### PR DESCRIPTION
**Pull request by 420kyle69**

### CODE REVIEW

**Comment by sloont** [comment]
can you provide a game with examples of different ways to set duration? would like to test all of the different cases to see if functionality is preserved

**Comment by 420kyle69** [comment]
In this game there are three different ways to set duration. https://www.modd.io/play/LW11on0Us/
Functionality will be preserved for the only case that works correctly now (manual input). For the other two cases (variable and function), setting duration will be changed to work as one would expect.

**Comment by m0dE** [comment]
@420kyle69 this PR makes sense to me. Can you resolve all conflicts? I'll merge it then

**Review by sloont — APPROVED** [review]

**Comment by 420kyle69** [comment]
@m0dE Looks like there are no conflicts.

**Pull request merged**
